#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "yarr"
name = "Yarr"
description.en = "Web-based feed aggregator"
description.fr = "Agrégateur de flux RSS"

version = "2.5~ynh1"

maintainers = []

[upstream]
license = "MIT"
code = "https://github.com/nkanaev/yarr"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/nkanaev/yarr/releases/download/v2.5/yarr_linux_amd64.zip"
    amd64.sha256 = "19bde8ce82070f924b1f49101890b6e2c47d0d0d70a7153117e3180749b35ce6"
    arm64.url = "https://github.com/nkanaev/yarr/releases/download/v2.5/yarr_linux_arm64.zip"
    arm64.sha256 = "bca8b66ece38ce7023af0f425aa1c6a94db5082b8007519de1596c54edd82b70"
    armhf.url = "https://github.com/nkanaev/yarr/releases/download/v2.5/yarr_linux_armv7.zip"
    armhf.sha256 = "5dc5c823c19714648d9f669212dc6f5cff9faf980db6e5e0552826155270596d"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.ports]

    [resources.apt]
    packages = "sqlite3"
