#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "yarr"
name = "Yarr"
description.en = "Web-based feed aggregator"
description.fr = "Agrégateur de flux RSS"

version = "2.6~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
code = "https://github.com/nkanaev/yarr"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/nkanaev/yarr/releases/download/v2.6/yarr_linux_amd64.zip"
    amd64.sha256 = "842d124099c68d47804e623c40129dc9b4d2b46514a13d91a393a02c49e01f95"
    arm64.url = "https://github.com/nkanaev/yarr/releases/download/v2.6/yarr_linux_arm64.zip"
    arm64.sha256 = "b2a71ee47e65153c6d611f6d36137daf786852e6715c008387889551677b4043"
    armhf.url = "https://github.com/nkanaev/yarr/releases/download/v2.6/yarr_linux_armv7.zip"
    armhf.sha256 = "2841c305a02400b59d77c72879f405527b11e7b565c755acbfab007c3fa97815"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.ports]

    [resources.apt]
    packages = "sqlite3"
