#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "yarr"
name = "Yarr"
description.en = "Web-based feed aggregator"
description.fr = "Agrégateur de flux RSS"

version = "2.5~ynh1"

maintainers = []

[upstream]
license = "MIT"
code = "https://github.com/nkanaev/yarr"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/nkanaev/yarr/archive/refs/tags/v2.5.tar.gz"
    sha256 = "0ea4b037b4485abe599ad2fe743f29adf9656dc34a8ffd0deefe3e0c863a37af"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.ports]

    [resources.apt]
    packages = "sqlite3"
